#!/bin/bash

# MAAS MCP Server - Environment Setup Script
#
# This script helps set up the environment variables needed to run the MAAS MCP Server.
# It creates a .env file based on user input or default values.
#
# Usage:
#   ./setup-env.sh [--defaults]
#
# Options:
#   --defaults    Use default values for all settings

# Set script to exit on error
set -e

echo "MAAS MCP Server - Environment Setup"
echo "==================================="

# Check if .env file already exists
if [ -f .env ] && [ "$1" != "--defaults" ]; then
  read -p "A .env file already exists. Do you want to overwrite it? (y/n): " overwrite
  if [ "$overwrite" != "y" ]; then
    echo "Setup cancelled. Existing .env file was not modified."
    exit 0
  fi
fi

# Function to get user input or use default
get_input() {
  local prompt="$1"
  local default="$2"
  local value=""
  
  if [ "$3" == "--defaults" ]; then
    value="$default"
  else
    read -p "$prompt [$default]: " input
    value="${input:-$default}"
  fi
  
  echo "$value"
}

# Get configuration values
if [ "$1" == "--defaults" ]; then
  echo "Using default values for all settings."
fi

MAAS_API_URL=$(get_input "Enter MAAS API URL" "https://your-maas-instance/MAAS" "$1")
MAAS_API_KEY=$(get_input "Enter MAAS API Key (consumer_key:token:secret)" "consumer_key:token:secret" "$1")
MCP_PORT=$(get_input "Enter MCP server port" "3000" "$1")
NODE_ENV=$(get_input "Enter Node environment (development, production, test)" "development" "$1")
LOG_LEVEL=$(get_input "Enter log level (trace, debug, info, warn, error, fatal)" "info" "$1")
MCP_PROTOCOL_VERSION=$(get_input "Enter MCP protocol version" "2024-11-05" "$1")
MCP_USE_LATEST_PROTOCOL=$(get_input "Use latest protocol version? (true, false)" "false" "$1")
CACHE_ENABLED=$(get_input "Enable caching? (true, false)" "true" "$1")
AUDIT_LOG_ENABLED=$(get_input "Enable audit logging? (true, false)" "true" "$1")

# Create .env file
cat > .env << EOF
# MAAS MCP Server Environment Configuration
# Generated by setup-env.sh on $(date)

# MAAS API Configuration
MAAS_API_URL=${MAAS_API_URL}
MAAS_API_KEY=${MAAS_API_KEY}

# Server Configuration
MCP_PORT=${MCP_PORT}
NODE_ENV=${NODE_ENV}
LOG_LEVEL=${LOG_LEVEL}

# MCP Protocol Configuration
MCP_PROTOCOL_VERSION=${MCP_PROTOCOL_VERSION}
MCP_USE_LATEST_PROTOCOL=${MCP_USE_LATEST_PROTOCOL}

# Cache Configuration
CACHE_ENABLED=${CACHE_ENABLED}
CACHE_STRATEGY=time-based
CACHE_MAX_SIZE=1000
CACHE_MAX_AGE=300
CACHE_RESOURCE_SPECIFIC_TTL={"Machine": 60, "Machines": 30, "Tags": 600}

# Audit Logging Configuration
AUDIT_LOG_ENABLED=${AUDIT_LOG_ENABLED}
AUDIT_LOG_INCLUDE_RESOURCE_STATE=false
AUDIT_LOG_MASK_SENSITIVE_FIELDS=true
AUDIT_LOG_SENSITIVE_FIELDS=password,token,secret,key,credential
AUDIT_LOG_TO_FILE=false
AUDIT_LOG_FILE_PATH=/var/log/maas-mcp-server/audit.log
EOF

echo "Environment configuration saved to .env file."
echo "You can now start the server with 'npm run dev' or 'npm start'."