name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (without v prefix)'
        required: true
        default: ''
      prerelease:
        description: 'Is this a pre-release?'
        type: boolean
        default: false

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Set version from tag
        if: github.event_name == 'push'
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Set version from input
        if: github.event_name == 'workflow_dispatch'
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Build for all platforms
        run: |
          mkdir -p release
          
          # Build for Linux (amd64)
          GOOS=linux GOARCH=amd64 go build -o release/maas-mcp-server-linux-amd64 cmd/server/main.go
          tar -czf release/maas-mcp-server-linux-amd64.tar.gz -C release maas-mcp-server-linux-amd64
          
          # Build for Linux (arm64)
          GOOS=linux GOARCH=arm64 go build -o release/maas-mcp-server-linux-arm64 cmd/server/main.go
          tar -czf release/maas-mcp-server-linux-arm64.tar.gz -C release maas-mcp-server-linux-arm64
          
          # Build for macOS (amd64)
          GOOS=darwin GOARCH=amd64 go build -o release/maas-mcp-server-darwin-amd64 cmd/server/main.go
          tar -czf release/maas-mcp-server-darwin-amd64.tar.gz -C release maas-mcp-server-darwin-amd64
          
          # Build for macOS (arm64)
          GOOS=darwin GOARCH=arm64 go build -o release/maas-mcp-server-darwin-arm64 cmd/server/main.go
          tar -czf release/maas-mcp-server-darwin-arm64.tar.gz -C release maas-mcp-server-darwin-arm64
          
          # Build for Windows (amd64)
          GOOS=windows GOARCH=amd64 go build -o release/maas-mcp-server-windows-amd64.exe cmd/server/main.go
          zip -j release/maas-mcp-server-windows-amd64.zip release/maas-mcp-server-windows-amd64.exe
          
          # Generate checksums
          cd release
          sha256sum *.tar.gz *.zip > checksums.txt
          cd ..

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease || false }}
          files: |
            release/*.tar.gz
            release/*.zip
            release/checksums.txt
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}